// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web {
    return FirebaseOptions(
      apiKey: _getEnvVar('WEB_API_KEY'),
      appId: _getEnvVar('WEB_APP_ID'),
      messagingSenderId: _getEnvVar('WEB_MESSAGING_SENDER_ID'),
      projectId: _getEnvVar('WEB_PROJECT_ID'),
      authDomain: _getEnvVar('WEB_AUTH_DOMAIN'),
      storageBucket: _getEnvVar('WEB_STORAGE_BUCKET'),
    );
  }

  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: _getEnvVar('ANDROID_API_KEY'),
      appId: _getEnvVar('ANDROID_APP_ID'),
      messagingSenderId: _getEnvVar('ANDROID_MESSAGING_SENDER_ID'),
      projectId: _getEnvVar('ANDROID_PROJECT_ID'),
      storageBucket: _getEnvVar('ANDROID_STORAGE_BUCKET'),
    );
  }

  static FirebaseOptions get ios {
    return FirebaseOptions(
      apiKey: _getEnvVar('IOS_API_KEY'),
      appId: _getEnvVar('IOS_APP_ID'),
      messagingSenderId: _getEnvVar('IOS_MESSAGING_SENDER_ID'),
      projectId: _getEnvVar('IOS_PROJECT_ID'),
      storageBucket: _getEnvVar('IOS_STORAGE_BUCKET'),
      iosBundleId: _getEnvVar('IOS_BUNDLE_ID'),
    );
  }

  static FirebaseOptions get macos {
    return FirebaseOptions(
      apiKey: _getEnvVar('IOS_API_KEY'),
      appId: _getEnvVar('IOS_APP_ID'),
      messagingSenderId: _getEnvVar('IOS_MESSAGING_SENDER_ID'),
      projectId: _getEnvVar('IOS_PROJECT_ID'),
      storageBucket: _getEnvVar('IOS_STORAGE_BUCKET'),
      iosBundleId: _getEnvVar('IOS_BUNDLE_ID'),
    );
  }

  static FirebaseOptions get windows {
    return FirebaseOptions(
      apiKey: _getEnvVar('WINDOWS_API_KEY'),
      appId: _getEnvVar('WINDOWS_APP_ID'),
      messagingSenderId: _getEnvVar('WINDOWS_MESSAGING_SENDER_ID'),
      projectId: _getEnvVar('WINDOWS_PROJECT_ID'),
      authDomain: _getEnvVar('WINDOWS_AUTH_DOMAIN'),
      storageBucket: _getEnvVar('WINDOWS_STORAGE_BUCKET'),
    );
  }

  static String _getEnvVar(String key) {
    final value = dotenv.env[key];
    if (value == null) {
      throw Exception('Environment variable $key is not set in .env file');
    }
    return value;
  }
}